# ========================================
# AUTH SERVICE CONFIGURATION (All Environments)
# ========================================

server:
  port: 8082
  servlet:
    context-path: /auth-service

spring:
  application:
    name: auth-service

# JWT Configuration (common)
jwt:
  access-token-expiry: 3600000      # 1 hour
  refresh-token-expiry: 86400000    # 24 hours

# Logging
logging:
  level: 
    com.devtam.authenticate: INFO