spring:
  application:
    name: auth-service
server:
  port: 8084
  servlet:
    context-path: /auth-service
logging:
  config: resources/logback-spring.xml

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
    doc-expansion: none
    filter: true
    show-extensions: true
    show-common-extensions: true
  show-actuator: false
  packages-to-scan: com.devtam.authenticate.application.controller
  paths-to-match: /**

eureka:
  client: 
    service-url:
      defaultZone: http://admin:Dev22x22@localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry:  true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 30